### ISSUE TITLE
micromamba is not recognized as an internal or external command 2.0.0

### ISSUE THREAD

**Issue by ktsitsi** [mamba-org/setup-micromamba#227]
Yesterday we noticed a failure in our CI only on the `windows-latest` runner where we were getting the following error:

```bash
'"C:\Users\runneradmin\micromamba\condabin\micromamba"' is not recognized as an internal or external command,
operable program or batch file.
```
using the  `mamba-org/setup-micromamba@v1`. while running a simple pre-commit check using the env.
```
Run micromamba run -n test pre-commit run -a
```

 Taking a look at the logs the only difference we notice is that `micromamba info`
was now fetching 
``` bash
libmamba version : 2.0.0
micromamba version : 2.0.0
```
We were able to resolve by pinning to `mamba-org/setup-micromamba@v1.9.0` with the `micromamba-version:  1.5.10-0` following similar approach as commented in https://github.com/mamba-org/setup-micromamba/issues/225

Runner Logs [here](https://github.com/TileDB-Inc/TileDB-BioImaging/actions/runs/11054794398/job/30746418843#step:3:1)

**Comment by jeremyleung521** [comment]
Was hoping `mamba=2.0.1` would fix this (there was a fix for a [windows bug on](https://github.com/mamba-org/mamba/pull/3484) `mamba activate`), but that doesn't seem to be case. Not sure if this is a problem on `setup-micromamba`'s end or regular `mamba`'s end?

Runner Logs: https://github.com/jeremyleung521/LPATH/actions/runs/11088430490/job/30931937962#step:4:362
Note: Can't see that it's running 2.0.1 in the windows jobs due to the order things are printed, but the other tests (macos, ubuntu) do say that 2.0.1 is pulled.

**Comment by pavelzw** [comment]
i would expect that this is a micromamba issue. wdyt @jjerphan?

**Comment by jjerphan** [comment]
It is. There's a problem with the activation script on Windows as of micromamba 2.0. We are currently addressing the problem.

**Comment by jjerphan** [comment]
2.0.2 is being released and should fix this issue.

**Comment by jeremyleung521** [comment]
> 2.0.2 is being released and should fix this issue.

Thank you! Just have to wait for `micromamba-releases` to update, then should be able to test!

**Comment by jeremyleung521** [comment]
I just updated to v2 (2.0.2) and still having the same problem... :/ Though this time, it's failing in the 'pip' section of the environment file. 

```
 Or to execute a single command in this environment, use:
  
      micromamba run -n test mycommand
  
  warning  libmamba You are using 'pip' as an additional package manager.
      Be aware that packages installed with 'pip' are managed independently from 'conda-forge' channel.
  
  Installing pip packages: pylcs, ray, timedinput, argparse-tui
  '"C:\Users\runneradmin\micromamba\condabin\micromamba"' is not recognized as an internal or external command,
  operable program or batch file.
  critical libmamba pip failed to install packages
```

Log file: https://github.com/jeremyleung521/LPATH/actions/runs/11182636779/job/31089361519#step:4:370


EDIT: It's this bug: https://github.com/mamba-org/mamba/issues/3467.

**Comment by jjerphan** [comment]
#234 resolved the cause of the problem.

Updating `setup-micromamba` to 2.0.0 should resolve the issue.

**Comment by jeremyleung521** [comment]
> #234 resolved the cause of the problem.
> 
> Updating `setup-micromamba` to 2.0.0 should resolve the issue.

Unfortunately it doesn't :( It works fine installing the conda packages, but I eventually get to the same error while trying to install the pip packages from the environment file. It's this error: https://github.com/mamba-org/mamba/issues/3467.

Logs: https://github.com/jeremyleung521/LPATH/actions/runs/11218580614/job/31182684438?pr=10#step:4:348

**Comment by ika-musuko** [comment]
I don't really know if this is good or not, but as a temporary fix, I copied the already existing `mamba.bat` to `micromamba.bat` inside the directory provided in the error, and was able to install packages from pip.

e.g. in my case I got this error:
```
'"C:\Users\ika\AppData\Roaming\mamba\condabin\micromamba"' is not recognized as an internal or external command,
operable program or batch file.
critical libmamba pip failed to install packages
```

In PowerShell, I did the following
```ps1
PS C:\> cd C:\Users\ika\AppData\Roaming\mamba\condabin
PS C:\Users\ika\AppData\Roaming\mamba\condabin> ls

    Directory: C:\Users\ika\AppData\Roaming\mamba\condabin

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          2024/10/29    18:02           1911 _mamba_activate.bat
-a---          2024/10/29    18:02            142 activate.bat
-a---          2024/10/29    18:02            778 mamba_hook.bat
-a---          2024/10/29    18:02            851 mamba.bat
PS C:\Users\sen\AppData\Roaming\mamba\condabin> cp mamba.bat micromamba.bat
```
Then I went back to the original directory, reran the micromamba create env command and everything worked fine.

**Comment by hameerabbasi** [comment]
This still happens in our CI: https://github.com/pydata/sparse/actions/runs/11721178880/job/33114861510?pr=805

**Comment by jjerphan** [comment]
Can you let us know if using micromamba 2.0.4 and setup-micromamba 2.0.2 fixed this problem?

**Comment by ktsitsi** [comment]
@jjerphan The issue on our end is fixed now.

**Comment by mtsokol** [comment]
> Can you let us know if using micromamba 2.0.4 and setup-micromamba 2.0.2 fixed this problem?

It's also fixed in `pydata/sparse`. Thank you!
